version: '3.18'

services:
    strapi:
        build:
            dockerfile: api.dockerfile
            context: ./dev/dockerfiles/api/
        ports:
            - '1337:1337'
    react:
        build:
            context: .
            dockerfile: ./dev/dockerfiles/react-app/react-app.dockerfile
        ports:
            - '3000:3000'
        volumes:
            - react-node_modules:/app/node_modules
            - .:/app
        stdin_open: true
        tty: true
        depends_on:
            - strapi
    utils-api:
        build:
            dockerfile: utils-api.dockerfile
            context: ./dev/dockerfiles/utils-api/
        ports:
            - 3001:3001
volumes:
    react-node_modules:
